version: '3.3'
services:

 postgres:
   image: postgres:latest
   environment:
     - POSTGRES_DB=django
     - POSTGRES_USER=django
     - POSTGRES_PASSWORD=django

 redis:
   image: redis:latest

 django:
   image: vitaliypavlovich/django:latest
   ports:
     - "8000:8000"
   volumes:
     - ./:/app/
   depends_on:
     - postgres
   environment:
     - POSTGRES_HOST=postgres
     - POSTGRES_PASS=django
   command: |
     python manage.py runserver 0.0.0.0:8000
