# Generated by Django 4.1.7 on 2023-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="excerpt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
