# Generated by Django 4.1.7 on 2023-04-05 18:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10),
        ),
    ]
