# Generated by Django 4.1.7 on 2023-04-06 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="excerpt",
            new_name="category",
        ),
    ]
