# Generated by Django 4.1.7 on 2023-04-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_product_price_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("IN_STOCK", "in_stock"), ("OUT_OF_STOCK", "out_of_stock")],
                default="IN_STOCK",
                max_length=32,
            ),
        ),
    ]
