name: Checks

on:
  push:
    branches:
      - main

jobs:
  checks:

    name: Run Django checks

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Cache pip
        uses: actions/cache@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters
        run: |
          flake8 shop/
          black shop/

      - name: Run Pytest suite
        run: |
          pytest --create-db --disable-warnings shop/
